### ISSUE TITLE
Using otherProperties to get Groupping 

### ISSUE THREAD

**Issue by jsturnio** [tudor-malene/Easygrid#135]
Hi,
I get Grouping working, using otherProperties, like here:
<code>
             &lt;grid:grid name="detalle" masterGrid="factura" childParamName="cfacturaId" jqgrid.width='690'  jqgrid.caption='Detalle'
                otherProperties="sortname: 'ctelefono.numeroCelular',  grouping:true,  groupingView : { groupField : ['ctelefono.grupop.nombre','ctelefono.numeroCelular'], groupSummary : [false,false], groupColumnShow : [true,true], groupText : ['{0}  SUM {montoTotal} - ({1})','{0} SUM {montoTotal}'] }" &gt; &lt;/grid:grid&gt;
</code>

However, if I try to use HTML tags inside groupText, I get an error, because it break the GSP code.
How I can get it working? (use HTML tags inside groupText, like &lt;b&gt; SUM XXXX &lt;/b&gt;

Thanks in advance, Jose

**Comment by tudor-malene** [comment]
Hi jsturnio,
Here is how I would write the grid:
```gsp
<grid:grid name="detalle" masterGrid="factura" childParamName="cfacturaId" >
    <grid:set width="690" caption="Detalle"/>
    <grid:set grouping="true" />
    <grid:set groupingView="${[:]}"/>
    <grid:set groupingView.groupField="['ctelefono.grupop.nombre','ctelefono.numeroCelular']" />
    <grid:set groupingView.groupSummary="[false,false]" />
    <grid:set groupingView.groupColumnShow="[true,true]" />
    <grid:set groupingView.groupText="['{0} SUM {montoTotal} - ({1})','{0} SUM {montoTotal}']" />
</grid:grid>
```

Let me know if it works.

**Comment by jsturnio** [comment]
Hi Tudor,  
Thanks for your answer.
I change my code, using the code suggested by you, is working great and the code is clear, however if I try to include some HTML tags inside groupText, I get the following error message:
*"Message
    Attribute value quote wasn't closed (groupingView.groupText="['<b)."*
I saw that jqGrid support HTML tags inside groupText, but is not supported here.

CODE that is working (without HTML tags inside groupText):
```HTML
                <grid:set sortname="ctelefono.numeroCelular" />
                <grid:set grouping="true" />
                <grid:set groupingView="${[:]}"/>
                <grid:set groupingView.groupField="['ctelefono.grupop.nombre','ctelefono.numeroCelular']" />
                <grid:set groupingView.groupSummary="[false,false]" />
                <grid:set groupingView.groupColumnShow="[false,false]" />
                <grid:set groupingView.groupText="['{0}     Total Grupo: \${montoTotal}  - ({1})','    {0}    Total Telefono: \${montoTotal}']" />

CODE that I am trying to get working: (including HTML tags)

                <grid:set sortname="ctelefono.numeroCelular" />
                <grid:set grouping="true" />
                <grid:set groupingView="${[:]}"/>
                <grid:set groupingView.groupField="['ctelefono.grupop.nombre','ctelefono.numeroCelular']" />
                <grid:set groupingView.groupSummary="[false,false]" />
                <grid:set groupingView.groupColumnShow="[false,false]" />
                <grid:set groupingView.groupText="['<b>{0}  </b>    Total Grupo: \${montoTotal}  - ({1})','    {0}    Total Telefono: \${montoTotal}']" />

**Comment by tudor-malene** [comment]
Would this work?

```gsp
<g:set var="groupText1">
   <b>{0}  </b>    Total Grupo: \${montoTotal}  - ({1})
</g:set>
...
<grid..
               <grid:set groupingView.groupText="['${groupText1}','    {0}    Total Telefono: \${montoTotal}']" />


```

**Comment by jsturnio** [comment]
Hi Tudor,
I tested using the g:set andI can not get it working, it say "$undefined" where the group text should be shown. 
When I see the page source code I get (only the part about jqGrid):
```HTML
<script type="text/javascript">jQuery(function(){
    jQuery("#detalle_table").jqGrid({
    url: '/clarof/efactura/detalleRows',
    loadError: easygrid.loadError,
    pager: '#detallePager',
    "viewrecords":true,"groupingView":{"groupField":["ctelefono.grupop.nombre","ctelefono.numeroCelular"],"groupSummary":[false,false],"groupColumnShow":[false,false],"groupText":["${groupText1}","    {0}    Total Telefono: ${montoTotal}"]},"caption":"Detalle","grouping":true,"sortname":"ctelefono.numeroCelular","datatype":"json","rowNum":100,"width":"890","rowList":[10,20,50],"multiSort":true,"height":325,
```    

As you can see, ${groupText1} is not replaced by the variable value (the variable is correctly set, because it show it's content,when is put directly in the GSP page). I tryied using a backslash (\${groupText1}, but with no luck

I get it working, if I "encode" in "otherProperties" the < and > character, and modify code in _jqGridRenderer to change again the encoded character to the original < and > character, but it is a very "dirty" solution.

**Comment by tudor-malene** [comment]
Are you sure you didn't escape the $?
As in:
```
<grid:set groupingView.groupText="['\${groupText1}'
```

**Comment by jsturnio** [comment]
No, I used without the escape. I used ${montoTotal} with the escape, because I had to use in this way to get it working, when I was testing with 'otherProperties'.  
Now is the same if I use escape or not in both variables (the source code always shown as in my last message. 
I can not get that ${groupText1} can be replaced by their value in this grid:set (but is replaced ok, when I put the variable in other place in the page)

**Comment by tudor-malene** [comment]
This should work:

```gsp
    <grid:set groupingView.groupText="[groupText1,'{0} SUM {montoTotal}']" />
```

**Comment by jsturnio** [comment]
Thanks Tudor!!, 
now is working fine, I am including the final version, maybe someone can find it usefull.
I had to escape the variable ${montoTotal}, due to is a variable for jqGrid, not for GSP (that share the same syntax):
```HTML
            <g:set var="groupText1"><b><h2>{0}      Total Grupo: ${'${montoTotal}'}  - ({1}) </h2></b></g:set>
            <g:set var="groupText2"><b>            {0}      Total Telefono: ${'${montoTotal}'}  - ({1}) </b></g:set>
            <grid:grid name="detalle" masterGrid="factura" childParamName="cfacturaId" jqgrid.width='890'  jqgrid.caption='Detalle' >
                <grid:set sortname="ctelefono.numeroCelular" />
                <grid:set grouping="true" />
                <grid:set groupingView="${[:]}"/>
                <grid:set groupingView.groupField="['ctelefono.grupop.nombre','ctelefono.numeroCelular']" />
                <grid:set groupingView.groupSummary="[false,false]" />
                <grid:set groupingView.groupColumnShow="[false,false]" />
                <grid:set groupingView.groupText= "[groupText1,groupText2]"  />
```
Thanks again, Jose
