### ISSUE TITLE
Additional Filteroperator(isNull, isNotNull, isNot, ...)

### ISSUE THREAD

**Issue by haryl** [tudor-malene/Easygrid#139]
Currently the following operators for filtering/searching is supported.
    EQ('equal'),
    NE('not equal'),
    LT('less'),
    LE('less or equal'),
    GT('greater'),
    GE('greater or equal'),
    BW('begins with'),
    BN('does not begin with'),
    IN('is in'),
    NI('is not in'),
    EW('ends with'),
    EN('does not end with'),
    CN('contains'),
    NC('does not contain')

what is missing is currently the isNull, isNotNull, ...
Especially the isNull would be very great because if eg. you define a filter query like email NC '@' you have no chance to get the entries were the email is null.

**Comment by tudor-malene** [comment]
Check version 1.7.0

I don't know why I missed those 2 operators in the first place.

**Comment by haryl** [comment]
awesome!! ;-) many thanks
