### ISSUE TITLE
Provide datatables column ordering per grid

### ISSUE THREAD

**Issue by marcosnils** [tudor-malene/Easygrid#142]
I've been trying to apply a default ordering to the grids but I don't find the way to do it independently for each grid. 

I was able to configure ordering globally by using this property in the EasyGridConfig file: 

```javascript 
defaults {
		
		dataTables {
			order = [13,'desc']
		}
}
```
But this will be applied to any grid.

Is there a way to specify the default ordering to each grid independently?

**Comment by tudor-malene** [comment]
As a general rule, everything that is configurable globally, should be also configurable per grid:

Try this:
```groovy
def yourGrid={
...
      dataTables {
            order = [13,'desc']
        }
...
      columns{
  ....
      }
}

```

**Comment by marcosnils** [comment]
I've tried that but it doesn't seem to work.

**Comment by tudor-malene** [comment]
Can you post the relevant generated html

**Comment by marcosnils** [comment]
@tudor-malene seems like the first time I tried I wasn't configuring it up correctly. I've just tried again and it worked with your example.

Thanks!.

btw: this should be documented somewhere as I've spent quite some time looking at the code to know how yo customize this stuff.
