### ISSUE TITLE
Inline editing - drop down

### ISSUE THREAD

**Issue by LyraSpark** [tudor-malene/Easygrid#52]
Hi,

How do we setup the inline editing to show the dropdown depending on values from a domain? say we have a set of type code and values from a different domain that the inline editing needs to use for a field. 

Thanks

**Comment by mkutti** [comment]
Hi,

I am having problem in the dropdown displaying the Value (FedEx,TNT etc) in the EasyGrid and dropdown becomes blank when I use dataUrl option.

Dropdown displays value correctly in the grid and dropdown and saves the key in the DB, if I hardcode the key,values. If I try to do the same using dataUrl it fails,

```
    jqgrid {
            edittype '"select"'

            formatter '"select"'

            editoptions '{dataUrl:"/testsite/listCircles"}'    //--> it fails which returns the same exact text below - value:"1:FedEx;2:InTime;3:TNT;4:ARAMEX"

            //editoptions '{value:"1:FedEx;2:InTime;3:TNT;4:ARAMEX"}'   // --> it works perfectly.

        } 
```

Please help, if there is a way to use dataUrl option.

Thanks
Mano

**Comment by mkutti** [comment]
I tried returning HTML as specified her http://www.trirand.com/jqgridwiki/doku.php?id=wiki%3acommon_rules.
1. Setting the editoptions dataUrl parameter The editoptions dataUrl parameter is valid only for element of edittype:select. The dataUrl parameter represent the url from where the html select element should be get.
   When this option is set, the element will be filled with values from the AJAX request. The data should be a valid HTML select element with the desired options - something like:

<select> 
<option value='1'>One</option> 
<option value='2'>Two</option> 
...
</select>

If I do that, Dropdown is OK. Displays the "values" and saves the "keys" correctly in the DB. However while displaying the easygrid the column becomes blank. (column displays "keys" in easy grid if I remove formatter in the jqgrid.I need to display "value" in the grid ). Thank you.
